# Generated by Django 2.0.2 on 2018-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20180203_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
