# Generated by Django 2.0.2 on 2018-02-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20180204_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_hash',
            new_name='slug',
        ),
    ]
