# Generated by Django 2.0.2 on 2018-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20180211_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
