# Generated by Django 2.0.2 on 2018-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20180222_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
